server:
  port: 1234

spring:
  application:
    name: main-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=assessment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    schemas: assessment

logging:
  level:
    root: INFO

config:
  login-expire: 100 # minute

google:
  auth:
    client-id: 283383699868-kud40qv9qa6qiu474tj6jgpacs472gpg.apps.googleusercontent.com
    client-secret: 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
    redirect-url: http://localhost:1234/login/redirect